version: "3.7"

services:
  # api-gateway:
  #   container_name: api-gateway
  #   build:
  #     context: ./api-gateway
  #     target: development
  #   volumes:
  #     - ./api-gateway:/usr/src/app
  #     - /usr/src/app/node_modules
  #   ports:
  #     - ${API_PORT}:${API_PORT}
  #   command: npm run start:dev
  #   networks:
  #     - webnet
  #   depends_on:
  #     - users-service

  # users-service:
  #   container_name: users-service
  #   build:
  #     context: ./users-service
  #     target: development
  #   volumes:
  #     - ./users-service:/usr/src/app
  #     - /usr/src/app/node_modules
  #   ports:
  #     - ${USERS_SERVICE_SERVER_PORT}:${USERS_SERVICE_SERVER_PORT}
  #   command: npm run start:dev
  #   networks:
  #     - webnet
  #   depends_on:
  #     - mongo-db
  #   environment:
  #     MONGO_URL: mongodb://$MONGO_USERNAME:$MONGO_PASSWORD@mongo-db:$MONGO_PORT/$MONGO_DATABASE?authSource=admin

  mongo-db:
    container_name: mongo-db
    image: mongo
    restart: "always"
    networks:
      - webnet
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - 0.0.0.0:${MONGO_PORT}:27017
    volumes:
      - mongodata:/data/db
networks:
  webnet:
volumes:
  mongodata:
